name: geoenv
channels:
  - conda-forge
dependencies:
# Python
  - python=3.10
# JupyterLab
  - jupyterlab
# Python scientific libraries
  - numpy
  - matplotlib
  - xarray
  - pyarrow
# Geospatial libraries
  - gdal>=3.0
  - libgdal-arrow-parquet>=3.0
  - rasterio>=1.3
  - geopandas
  - rioxarray
  - xarray-spatial
  - earthpy
  - descartes # necessary for geopandas plotting
  - pystac-client
  - python-graphviz
  - visidata
  - geojson